### ISSUE TITLE
Error with argument for torch.Size()

### ISSUE THREAD

**Issue by maxspahn** [NVlabs/storm#3]
Hi,

great work with this repository. Really appreciated the fact that you put it open-source.
I encountered a problem when running the script due to a potential bug in mpc/control.

After the installation according to your instruction, everything works smooth until I encounter the following error:
```bash
self.sample_shape = torch.Size([self.num_nonzero_particles - 2], device=self.tensor_args['device'])
TypeError: tuple() takes at most 1 argument (2 given)
```

I removed the second argument in two locations:
https://github.com/NVlabs/storm/blob/cf056514659cab9c5c7ac9d850eae7c56a660726/storm_kit/mpc/control/olgaussian_mpc.py#L112
https://github.com/NVlabs/storm/blob/cf056514659cab9c5c7ac9d850eae7c56a660726/storm_kit/mpc/control/sample_libs.py#L315

With these modifications, everything works smoothly.
It might be related to the torch version. I have installed torch v.1.10.0 (automatically through your setup file)

Let me know if you have run into this problem, or tell me how I could fix it on my side.

Best,
Max.

**Comment by balakumar-s** [comment]
Thanks, yes with new pyTorch versions, `torch.Size` cannot be on the GPU. I will push a fix soon addressing this.
