### ISSUE TITLE
Problem with franka_reacher.py example

### ISSUE THREAD

**Issue by kaustabpal** [NVlabs/storm#6]
I am trying to run the example file python franka_reacher.py. But on running the red mug falls through the base and floats below. (Screenshot attached). Kindly let me know how to fix this please.
![Screenshot from 2022-08-18 22-24-17](https://user-images.githubusercontent.com/15041798/185451886-de81d4cd-dcd9-4e3b-8b7d-176c41ae3724.png)

**Comment by balakumar-s** [comment]
Can you share a video of this happening? This happens when gravity is enabled for an object.

**Comment by kaustabpal** [comment]
Please find the video here: [video](https://youtu.be/uBRj1aQPV3A)
This is the settings of the environment. The gravity is set to -9.8. 
![Screenshot from 2022-08-28 18-58-24](https://user-images.githubusercontent.com/15041798/187076362-b299e39d-a3f5-443e-bf81-5a7ad03fd503.png)
I set the gravity to 0 and adjusted the position of the mug above the table but then it just floats above the table. The robot arm however reaches for the mug which means the algorithm is working.
