### ISSUE TITLE
Weird motion of the target mug in franka_reacher

### ISSUE THREAD

**Issue by alaflaquiere-sony** [NVlabs/storm#8]
Thank you for providing your code.

I've been trying to run the `franka_reacher.py` demo, but I'm getting a surprising behavior from the target (red) mug. It falls through the table, and then progressively slides to a corner of the environment (see attached video).

Is that the expected behavior?
I'm guessing it is not, especially because the behavior of the robot is significantly different when setting the `vis_ee_target` variable to `False`. In that case, the robot tries to reach an (invisible) target in front of it, which looks much more like a proper demo.

Any help with this weird behavior?

https://user-images.githubusercontent.com/114128734/193214376-abbba2b0-ab62-455f-a406-dd6ffbfe38db.mp4

**Comment by kaustabpal** [comment]
From the Actor dropdown menu, select the target_ee_mug and then go to Pose Override to manipulate the position of the target mug.

**Comment by alaflaquiere-sony** [comment]
Yes, I did this. But I wondered if that was the desired behavior, as I would have expected a predefined motion for the target mug.
